function whifun_save_parameters(save_folder,save_name,...
                                data_path,output_folder,bids_check,...
                                comm_sess_name,comm_subj_name,...
                                func_folder_name,anat_folder_name,...
                                func_data_name,anat_data_name,...
                                n_vol_dis,...
                                max_fd,mean_fd,greater_than_20,...
                                Seg_dartel_drop,...
                                CSF_thres,...
                                Reg_drop,n_pca,motion_reg,...
                                filter_check,filter_lp,filter_hp,...
                                smooth_drop,smooth_fwhm,...
                                vox)

save(fullfile(save_folder,save_name),"data_path","output_folder",'bids_check',...
                                    'comm_sess_name','comm_subj_name',...
                                    'func_folder_name','anat_folder_name',...
                                    'func_data_name',"anat_data_name",...
                                    'n_vol_dis',...
                                    'max_fd','mean_fd','greater_than_20',...
                                    'Seg_dartel_drop',...
                                    'CSF_thres',...
                                    'Reg_drop','n_pca','motion_reg',...
                                    'filter_check','filter_lp','filter_hp',...
                                    "smooth_drop","smooth_fwhm",...
                                    "vox")