function write_error(exception,quality_control_path,name)
%WRITE_ERROR Displays and optionally logs MATLAB exceptions to a file.
%
%   WRITE_ERROR(exception) catches a MATLAB MException object and cleanly
%   prints the error identifier, message, timestamp, and stack trace (with 
%   line numbers) directly to the MATLAB Command Window.
%
%   WRITE_ERROR(exception, quality_control_path, name) performs the
%   command window display and additionally appends the error details to a 
%   text file. The file is saved inside an 'Error_Info' folder within the 
%   provided quality_control_path. The text file is named using the 
%   format: '<name>_error_info.txt'. If the target directory does not 
%   exist, the function creates it automatically.
%
%   Inputs:
%       exception            - MATLAB MException object generated by a 
%                              try/catch block.
%       quality_control_path - (Optional) String or char array specifying 
%                              the base directory where the 'Error_Info' 
%                              folder should be located/created.
%       name                 - (Optional) String or char array representing 
%                              the subject name or run identifier. Used 
%                              for the text file naming and logged inside 
%                              the file.
%
%   Example:
%       try
%           % some code that fails
%           error('MyCode:BadInput', 'Invalid input detected.');
%       catch ME
%           write_error(ME, 'C:\Data\QC', 'Subject_01');
%       end
%   Author: Pratik Jain
if nargin == 1
    quality_control_path = '';
    name = '';
end

% Display in command
fprintf([ '<strong>' exception.identifier '</strong> \n'])
fprintf(['Error Message :' '<strong>' exception.message '</strong> \n'])
fprintf(['Code ran on ' char(datetime) '\n \n']);
for err_i = 1:length(exception.stack)
    fprintf(['Error using ' '<strong>' exception.stack(err_i).name '</strong>' ' (line ' num2str(exception.stack(err_i).line) ')\n' ])
end

if ~isempty(quality_control_path) && ~isempty(name)

    % write to file
    out_path = fullfile(quality_control_path,'Error_Info');
    if ~exist(out_path,"dir")
        mkdir(out_path)
    end
    err_fileID = fopen(fullfile(out_path,[name '_error_info.txt']),'a');

    fprintf(err_fileID,'#####################################################################################################################\n \n');
    fprintf(err_fileID, ['Subject Name: ' name '\n \n']);
    fprintf(err_fileID,['Code ran on ' char(datetime) '\n \n']);
    fprintf(err_fileID,[ exception.identifier ' \n']);
    fprintf(err_fileID,['Error Message :'  exception.message '\n']);

    for err_i = 1:length(exception.stack)
        fprintf(err_fileID,'%s',['Error using ' exception.stack(err_i).name ' (line ' num2str(exception.stack(err_i).line) ')\n' ]);
    end
    fprintf(err_fileID,'\n');
    fclose(err_fileID);
end
